#!/bin/bash

# Do not run this script manually; use crystallise instead.

#Script should run as root.
[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"

#Script should exit if any operation fails.
set -e

echo "Arguments: " "$@"

echo "Configuration: "

cat "$HOME"/config.txt

crystalTitle=$(sed '1q;d' "$HOME"/config.txt)
export crystalTitle
crystalCollection=$(sed '2q;d' "$HOME"/config.txt)
export crystalCollection
crystallisePassphrase=$(sed '3q;d' "$HOME"/config.txt)
export crystallisePassphrase
crystalTempdir=$(sed '4q;d' "$HOME"/config.txt)
export crystalTempdir

export CrystalID="$1"

echo "Environment: "

uname -ap

echo "Environment variables: "

printenv

echo "The crystal will have the following address when it is ready: $CrystalID"

printf "%s" "$crystallisePassphrase" > "$crystalTempdir/$CrystalID".tmp

echo "Building local index..."

hashdeep -c md5,sha1,sha256 -o fbcpsde "$@" "$crystalTempdir/$CrystalID" | tee "$crystalTempdir/$CrystalID.local.idx"

echo "Building deep index..."

hashdeep -c md5,sha1,sha256 -o fbcpsde -r "$@" "$crystalTempdir/$CrystalID" | tee "$crystalTempdir/$CrystalID.deep.idx"

tar -cv -P --format pax -f "$crystalTempdir/$@" "$crystalTempdir/$CrystalID" "$crystalTempdir/$CrystalID.local.idx" "$crystalTempdir/$CrystalID.deep.idx" "$crystalTempdir/$CrystalID.local.idx" "$crystalTempdir/$CrystalID.deep.idx" "$crystalTempdir/$CrystalID.tmp" "$crystalTempdir/$CrystalID.tmp"

script /dev/null xz "-k -C sha256 -9 -e -v $crystalTempdir/$CrystalID.pax"

rm -v "$crystalTempdir/$CrystalID".pax

gpg --yes -c -v --cipher-algo AES256 --batch --passphrase-file "$crystalTempdir/$CrystalID".tmp "$crystalTempdir/$CrystalID".pax.xz

rm -v "$crystalTempdir/$CrystalID".pax.xz

mv "$crystalTempdir/$CrystalID".pax.xz.gpg "$crystalTempdir/$CrystalID".coal5

echo "Computing checksum..."

hashdeep -c md5,sha1,sha256 -o fbcpsde "$crystalTempdir/$CrystalID".coal5 | tee "$crystalTempdir/$CrystalID.checksums"

echo "Sending..."

script /dev/null ia "upload $CrystalID --retries=10 --metadata=subject:Uploaded using Crystallise $crystalliseVersion --metadata=subject:1EA21BD8-DB7E-11E5-9733-728C37852114 --metadata=subject:$crystalTitle --metadata=collection:$crystalCollection --delete $crystalTempdir/$CrystalID.coal5"

echo "Retrieving remote index..."

wget --save-headers --output-document - "https://archive.org/metadata/$CrystalID/" | tee ./"$CrystalID.json"

script /dev/null xz "-C sha256 -9 -e -v $crystalTempdir/$CrystalID.json"

echo "Copying indices..."

rsync -av --progress --checksum "$crystalTempdir/$CrystalID.local.idx" "$crystalTempdir/$CrystalID.deep.idx" "$crystalTempdir/$CrystalID.checksums" "$crystalTempdir/$CrystalID.json.xz" /Ember\ Media\ Library/Futuramerlin\ Projects/Data/Crystal\ Index/

echo "Uploaded to https://archive.org/download/$CrystalID"

#Delete everything except log
echo "Cleaning up..."
yes | rm -rv "${@:2}"

#Clear the screen
printf "\033c"

echo "Done sending! The new crystal's address is:"
echo "$CrystalID"