#!/bin/bash
# Crystallise

#Script must be run as root.

#Usage: crystallise-update

[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"

#Script should NOT exit if any operation fails.

CrystalID=CrystalliseUpdate-$(date +%Y.%m.%d.%H.%M.%S.%N)-$(xxd -pu <<< "$(date +%z)")-$(python -c 'import uuid; print str(uuid.uuid4())')
export CrystalID

cp -v /usr/bin/crystallise-update /usr/bin/crystallise-update.old.$CrystalID
crystallise /usr/bin/crystallise /usr/bin/crystallise-logsession /usr/bin/crystallise-internal-xz /usr/bin/crystallise-internal-ia /usr/bin/crystallise-internal-xz-b /usr/bin/decrystallise /usr/bin/decrystallise-logsession /usr/bin/crystallise-update.old.$CrystalID
mkdir -v ~/$CrystalID.tmp
cd ~/$CrystalID.tmp
wget https://raw.githubusercontent.com/ethus3h/ember/master/ember-satellite-projects/crystallise/crystallise
wget https://raw.githubusercontent.com/ethus3h/ember/master/ember-satellite-projects/crystallise/crystallise-update
wget https://raw.githubusercontent.com/ethus3h/ember/master/ember-satellite-projects/crystallise/crystallise-logsession
wget https://raw.githubusercontent.com/ethus3h/ember/master/ember-satellite-projects/crystallise/crystallise-internal-xz
wget https://raw.githubusercontent.com/ethus3h/ember/master/ember-satellite-projects/crystallise/crystallise-internal-ia
wget https://raw.githubusercontent.com/ethus3h/ember/master/ember-satellite-projects/crystallise/crystallise-internal-xz-b
wget https://raw.githubusercontent.com/ethus3h/ember/master/ember-satellite-projects/crystallise/decrystallise
wget https://raw.githubusercontent.com/ethus3h/ember/master/ember-satellite-projects/crystallise/decrystallise-logsession
chmod +x ./*
cp -v ./* /usr/bin/
cd ~
crystallise ~/$CrystalID.tmp
mkdir -v ~/$CrystalID.tmp
cd ~/$CrystalID.tmp
wget https://raw.githubusercontent.com/ethus3h/ember/master/ember-satellite-projects/crystallise/crystallise-rescue
chmod +x ./*
cp -v ./* /usr/bin/
cd ~
echo "Done!"