#!/bin/bash

# Do not run this script manually; use crystallise instead.

#Script should run as root.
[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"

#Script should exit if any operation fails.
set -e

echo "Arguments: " "$@"

echo "Configuration: "

cat "$HOME"/config.txt

crystalTitle=$(sed '1q;d' "$HOME"/config.txt)
export crystalTitle
crystalCollection=$(sed '2q;d' "$HOME"/config.txt)
export crystalCollection
crystallisePassphrase=$(sed '3q;d' "$HOME"/config.txt)
export crystallisePassphrase

export CrystalID="$1"

echo "The crystal will have the following address when it is ready: $CrystalID"

printf "%s" "$crystallisePassphrase" > ./"$CrystalID".tmp

tar -cv --format pax -f ./"$CrystalID".pax "$@" $(pwd)/$CrystalID

script /dev/null xz -k -C sha256 -9 -e -v ./"$CrystalID".pax

rm -v ./"$CrystalID".pax

gpg --yes -c -v --cipher-algo AES256 --batch --passphrase-file "$CrystalID".tmp ./"$CrystalID".pax.xz

rm -v ./"$CrystalID".pax.xz

mv ./"$CrystalID".pax.xz.gpg ./"$CrystalID".coal5

echo "Sending..."

script /dev/null ia upload "$CrystalID" --metadata="subject:Uploaded using Crystallise $crystalliseVersion; 1EA21BD8-DB7E-11E5-9733-728C37852114; $crystalTitle" --metadata="collection:$crystalCollection" --delete ./"$CrystalID".coal5

echo "Uploaded to https://archive.org/download/$CrystalID"

#Delete everything except log
echo "Cleaning up..."
rm -rv "${@:2}"

#Upload log file and passphrase file
# crystallise-logsession "$CrystalID" "$CrystalID".tmp 2>&1 /dev/null

# rm -v "$CrystalID" ./"$CrystalID".tmp

rm -v ./"$CrystalID".tmp

#Clear the screen
printf "\033c"

echo "Done! The new crystal's address is:"
echo "$CrystalID"