#!/bin/bash
ia upload "$CrystalID" --retries=10 --metadata=subject:Uploaded using Crystallise "$crystalliseVersion" --metadata=subject:1EA21BD8-DB7E-11E5-9733-728C37852114 --metadata=subject:"$crystalTitle" --metadata=collection:"$crystalCollection" --delete "$crystalTempdir/$CrystalID".coal5
