#!/bin/bash

# Do not run this script manually; use decrystallise instead.

#Script should run as root.
[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"

#Script should exit if any operation fails.
set -e

echo "Arguments: " "$@"

crystallisePassphrase=$(sed '3q;d' "$HOME"/config.txt)
export crystallisePassphrase
crystalTempdir=$(sed '4q;d' "$HOME"/config.txt)
export crystalTempdir

export CrystalID="$1"

echo "Environment: "

uname -ap

echo "Environment variables: "

printenv

echo "Crystal address: $CrystalID"

printf "%s" "$crystallisePassphrase" > "$crystalTempdir/$CrystalLogID".tmp

echo "Receiving..."

wget -O "$crystalTempdir/$CrystalLogID".pax.xz.gpg "https://archive.org/download/$CrystalID/$CrystalID".coal5

gpg --yes --batch --passphrase-file "$crystalTempdir/$CrystalLogID".tmp "$crystalTempdir/$CrystalLogID".pax.xz.gpg

rm -v "$crystalTempdir/$CrystalLogID".pax.xz.gpg

unxz "$crystalTempdir/$CrystalLogID".pax.xz

mkdir -v "$crystalTempdir/$CrystalLogID.tmpd"

mv -v "$crystalTempdir/$CrystalLogID".pax "$crystalTempdir/$CrystalLogID.tmpd/"

tar -xvf "$crystalTempdir/$CrystalLogID.tmpd"/"$CrystalLogID".pax -C "$crystalTempdir/$CrystalLogID.tmpd"/

rm -v "$crystalTempdir/$CrystalLogID.tmpd"/"$CrystalLogID".pax

mv -v "$crystalTempdir/$CrystalLogID" "$crystalTempdir/$CrystalLogID".log

mv -v "$crystalTempdir/$CrystalLogID.tmpd" "$crystalTempdir/$CrystalLogID"

#Clear the screen
printf "\033c"

echo "Done receiving! The crystal has been extracted to:"
echo "$crystalTempdir/$CrystalLogID"