#!/bin/bash
# decrystallise

# See crystallise for requirements.

#Usage: decrystallise <crystal-address>

[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"

#Script should exit if any operation fails.
set -e

CrystalLogID=Decrystallised-$(python -c 'import uuid; print str(uuid.uuid4())')-$(date +%Y.%m.%d.%H.%M.%S.%N)-$(xxd -pu <<< "$(date +%z)")
export CrystalLogID

decrystallise-logsession "$@" 2>&1 | tee -a "$CrystalLogID"

echo "Finishing; please wait for completion..."
xz -C sha256 -9 -e "$CrystalLogID"
rsync -aq --checksum "$CrystalLogID".xz /Ember\ Media\ Library/Futuramerlin\ Projects/Data/Crystal\ Index/"$CrystalLogID".log.xz
gpg --yes -c -q --cipher-algo AES256 --batch --passphrase-file "$CrystalLogID".tmp ./"$CrystalLogID".xz
rm ./"$CrystalLogID".tmp
mv ./"$CrystalLogID".xz.gpg ./"$CrystalLogID".coal5-log
ia upload "$CrystalLogID" --metadata="subject:Uploaded using Decrystallise $crystalliseVersion; Decrystallise log; log; logs; 1EA21BD8-DB7E-11E5-9733-728C37852114; $1" --metadata="collection:$crystalCollection" --delete ./"$CrystalLogID".coal5-log
echo "Done!"
