#!/bin/bash
# Warcdealer
# Version:
export warcdealerVersion='2.0.7'

#Requires ia (https://pypi.python.org/pypi/internetarchive) to be installed and to have been configured since being updated to version 1.0.2.

#Script must be run as root.

#Usage: warcdealer
#The file(s) to be uploaded must be within the current directory.

[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"

#Script should exit if any operation fails.
set -e

WarcdealerPackID=Warcdlr-$(date +%Y-%m-%d-%H-%M-%S-%N)-$(xxd -pu <<< "$(date +%z)")-$(python -c 'import uuid; print str(uuid.uuid4())')

echo "Working..."

ls -a -B -l -R -i . | tee "./$WarcdealerPackID.listing"

find . -name "wpull.db" -o -name "*.cdx" -exec xz -C sha256 -9 -e -v '{}' \;

find . -name "*.warc" -o -name "*.warc.*" -o -name "$WarcdealerPackID.listing" -o -name "wpull.db.xz" -o -name "wpull.db" -o -name "*.megawarc*" -o -name "*.cdx.xz" -o -name "*.cdx" -exec ia upload "$WarcdealerPackID" --checksum --retries=10 --metadata="subject:Uploaded using Warcdealer $warcdealerVersion" --metadata="subject:002F9DCE-F064-11E5-99AD-6BFA56EF8172" --metadata="title:Warcdealer pack $WarcdealerPackID" --metadata="subject:$WarcdealerPackID" --metadata="collection:opensource" --delete '{}' \;

echo "Done; sleeping 3 minutes..."
