#!/bin/bash
#Requires html-minifier: https://www.npmjs.com/package/html-minifier
#Requires html5-tidy: https://github.com/htacg/tidy-html5
#Requires minifier: https://www.npmjs.com/package/minifier
#Requires hypertoc: sudo cpan -f -i HTML::GenToc

[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"

shopt -s extglob

echo "Preparing environment..."
rm -r "../built"
mkdir "../built"
echo '<nav id="toc">' > "../built/0h.tmp"
echo '</nav>' > "../built/0f.tmp"
echo "Copying assets..."
cp -r ./assets/* ./assets/.[^.]* "../built/"
(
	cd "content" || exit
	traversedirectory() {
		echo "Entered directory $1..."
		for i in "$1"/*; do
			if [[ -d "$i" ]]; then
				if ! [[ "$i" == "." ]]; then
					if ! [[ "$i" == ".." ]]; then
						echo "Entering directory $i..."
						traversedirectory "$i"
					fi
				fi
			else
				echo "Building page: $i"
				../scripts/build-page "$i"
			fi
		done
	}
	traversedirectory "."
)
echo "Processing CSS..."
cp "./assets/m.css" "../built/m.css"
tr '\n' ' ' < "../built/m.css" > "../built/1.tmp"
tr '\t' ' ' < "../built/1.tmp" > "../built/2.tmp"
tr '\r' ' ' < "../built/2.tmp" > "../built/3.tmp"
tr -s " " < "../built/3.tmp" > "../built/m.css"
minify --no-comments -o "../built/m.css" "../built/m.css" > /dev/null
rm ../built/*.tmp
rm ../built/*.html
cp "../built/m.css" "/m.css"
echo "Done!"
