#!/bin/bash
#Requires html-minifier: https://www.npmjs.com/package/html-minifier
#Requires html5-tidy: https://github.com/htacg/tidy-html5
#Requires minifier: https://www.npmjs.com/package/minifier

rm -rv "../built";
mkdir "../built/";
cp -rv ./assets/* "../built/";

cd "content";
traversedirectory() {
	echo "Entered directory $1...";
	for i in "$1"/*; do
		if [ -d "$i" ]; then
			if ! [ "$i" == "." ]; then
				if ! [ "$i" == ".." ]; then
					echo "Entering directory $i...";
					traversedirectory "$i";
				fi;
			fi;
		else
			echo "Building page: $i";
			../scripts/build-page "$i";
		fi;
	done;
}
traversedirectory ".";
cd ..;

cp -v "./assets/m.css" "../built/m.css";
tr '\n' ' ' < "../built/m.css" > "../built/1.tmp";
tr '\t' ' ' < "../built/1.tmp" > "../built/2.tmp";
tr '\r' ' ' < "../built/2.tmp" > "../built/3.tmp";
tr -s " " < "../built/3.tmp" > "../built/m.css";
minify --no-comments -o "../built/m.css" "../built/m.css";
rm -v ../built/*.tmp;
rm -v ../built/*.html;
