#!/bin/bash
#Requires html-minifier: https://www.npmjs.com/package/html-minifier
#Requires html5-tidy: https://github.com/htacg/tidy-html5
#Requires minifier: https://www.npmjs.com/package/minifier

for file in ./*.htm;
do ./scripts/build-page-fn "$file";
done;

rm -rv "../built/";
mkdir "../built/";
cp -v ./assets/* "../built/";
cp -v "./assets/m.css" "../built/m.css";
tr '\n' ' ' < "../built/m.css" > "../built/1.tmp";
tr '\t' ' ' < "../built/1.tmp" > "../built/2.tmp";
tr '\r' ' ' < "../built/2.tmp" > "../built/3.tmp";
tr -s " " < "../built/3.tmp" > "../built/m.css";
minify --no-comments -o "../built/m.css" "../built/m.css";
rm -v ../built/*.tmp;
